Repository topcoder-platform/topcoder-react-ui-kit, pull requests merged in 2019-07, with the labels that each got.

#16 MSFT-86
  src/styles/_mixins/variables.scss
Labels: Accessibility, Code Review Passed, Merged for QA

#14 2743 fix
  src/styles/_mixins/variables.scss
Labels: Accessibility, Code Review Passed

#10 2885 fix
  src/styles/_mixins/variables.scss
Labels: Accessibility, Code Review Passed

#17 pr from 11
  src/styles/_mixins/variables.scss
Labels: Code Review Passed, Merged for QA

#19 Color palette fix
  src/styles/_mixins/variables.scss
Labels: Merged for QA

#9 MSFT-85
  src/shared/components/buttons/themes/primary.scss
Labels: Merged for QA

#8 MSFT-83
  src/shared/components/buttons/themes/danger.scss
Labels: Accessibility, Merged for QA

#21 Update colors
  src/styles/_mixins/variables.scss
Labels: Accessibility, Code Review Passed, Merged for QA

#20 Issue 2871 fix
  src/shared/components/tags/primary/data-science.scss
  src/shared/components/tags/primary/design.scss
  src/shared/components/tags/primary/development.scss
Labels: Accessibility, Code Review Passed, Merged for QA
